---
name: Test Suite

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests-linux:
    name: "Python ${{ matrix.python-version }} - Ubuntu"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10.0-rc.1"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: "scripts/install"
      - name: "Run linting checks"
        run: "scripts/check"
      - name: "Build package & docs"
        run: "scripts/build"
      - name: "Run tests"
        run: "scripts/test"
      - name: "Enforce coverage"
        run: "scripts/coverage"

  tests-windows:
    name: "Python ${{ matrix.python-version }} - Windows"
    runs-on: "windows-latest"

    strategy:
      matrix:
        python-version: [ "3.6", "3.7", "3.8", "3.9", "3.10.0-rc.1" ]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: "scripts/win/install.ps1"
      - name: "Run linting checks"
        run: "scripts/win/check.ps1"
      - name: "Build package & docs"
        run: "scripts/win/build.ps1"
      - name: "Run tests"
        run: "scripts/win/test.ps1"
      - name: "Enforce coverage"
        run: "scripts/win/coverage.ps1"
